name: Main

on:
  repository_dispatch:
    types: [test]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Build
        run: echo ${{ github.sha }} > Release.txt
        
      - name: Test
        run: cat Release.txt
        
      - name: Upload Firmware To Release
        uses: SuLingGG/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repository: SuLingGG/OpenWrt-Release
          tag_name: Test-Release
          files: |
            Release.txt
