name: Upload & Download

on:
  workflow_dispatch:

jobs:
  Upload:
    runs-on: ubuntu-18.04
    
    steps:
    - name: Rclone Upload
      env:
        RCLONE_REMOTE: ${{ secrets.RCLONE_REMOTE }}
      run: |
        cd $OPENWRTROOT
        curl https://rclone.org/install.sh | sudo bash
        mkdir -p ~/.config/rclone/
        cat << EOF > ~/.config/rclone/rclone.conf
        ${{ secrets.RCLONE_CONFIG }}
        EOF
        echo 123 > 123.txt
        rclone copy 123.txt $RCLONE_REMOTE:$(date +"%Y-%m-%d")/lean
        echo "::warning file=Firmware-GoogleDrive::Download Link: https://drive.google.com/drive/folders/1SkNpJkhmG8veheL3ADVFoVTkvfhWjW0P"
        
  Download:
    needs: [Upload]
    runs-on: ubuntu-18.04

    steps:
        - name: Create Folder
          run: |
            sudo apt-get upgrade && sudo apt-get install tree -y
            mkdir -p openwrt
        - name: Download Files
          uses: actions/download-artifact@v2
          id: download
          with:
            name: 'rclone-false.conf'
            path: openwrt

        - name: Echo Download Path
          run: echo ${{steps.download.outputs.download-path}}
          
        - name: Tree
          run: |
            cd openwrt
            tree .
