name: Upload & Download

on:
  workflow_dispatch:

jobs:
  Upload:
    runs-on: ubuntu-18.04
    
    steps:
    - name: Rclone Upload
      env:
        RCLONE_REMOTE: ${{ secrets.RCLONE_REMOTE }}
      if: env.RCLONE_REMOTE != ''
      run: |
        cd $OPENWRTROOT
        curl https://rclone.org/install.sh | sudo bash
        mkdir -p ~/.config/rclone/
        cat << EOF > ~/.config/rclone/rclone.conf
        ${{ secrets.RCLONE_CONFIG }}
        EOF
        echo 123 > 123.txt
        rclone copy 123.txt $RCLONE_REMOTE:$(date +"%Y-%m-%d")/lean
        echo "::warning file=Firmware-GoogleDrive::Download Link: https://drive.google.com/drive/folders/1SkNpJkhmG8veheL3ADVFoVTkvfhWjW0P"
